Hw 2
Ostos-Alexander/Homework1 pull request #2
Opened 2017-03-10 15:36 UTC by Ostos-Alexander

I have done hometask2

2017-03-10 19:06 UTC, pro100jas commented on homework2/ostos_task_2.html
> +
не зовсім зрозумів, навіщо тобі пусті aside

2017-03-10 19:07 UTC, pro100jas commented on homework2/ostos_task_2.html
> +	</div>
так не робиться, краще юзай тег menu або ul

2017-03-10 19:07 UTC, pro100jas commented on homework2/ostos_task_2.html
> +		</div>
Те ж саме, читай комент вище

2017-03-10 19:08 UTC, pro100jas commented on homework2/ostos_task_2.html
> +    		<div class="text">Lorem Ipsum - це текст-"риба", що використовується в друкарстві та дизайні. Lorem Ipsum є, фактично, стандартною "рибою" аж з XVI сторіччя, коли невідомий друкар взяв шрифтову
не роби таке довге речення в 1 стрічку, краще зроби абзац, але щоб не виходило за межі екрану

2017-03-10 19:08 UTC, pro100jas commented on homework2/ostos_task_2.html
> +	</div>
читай коменти вище на рахунок цих штук))

2017-03-10 19:09 UTC, pro100jas commented on homework2/ostos_task_2.html
> +	</div>
не треба такого робити) читай вище

2017-03-10 19:11 UTC, pro100jas commented on homework2/ostos_task_2.css
> +.technics:hover {
в тебе з'їжджає побутова техніка

2017-03-10 19:13 UTC, pro100jas commented on homework2/ostos_task_2.css
> +.tape {
там має бути інший колір для верхньої менюшки

2017-03-10 19:13 UTC, pro100jas commented on homework2/ostos_task_2.css
> +}
немає тіні від документа

2017-03-10 19:15 UTC, pro100jas commented on homework2/ostos_task_2.html
> +			<font><a class="fc1" href="">Главная</a></font>
називай класи по контенту

2017-03-10 19:15 UTC, pro100jas commented on homework2/ostos_task_2.html
> +			<font class="fc12"><a class="fc1" href="">Товари</a></font>
тут те ж саме і далі теж)

2017-03-10 19:16 UTC, pro100jas commented on homework2/ostos_task_2.html
> +		<div class="flex">
знову ж неправильна назва

2017-03-10 19:20 UTC, pro100jas commented on homework2/ostos_task_2.html
> +		<div class="flex fc15">
💩

2017-03-17 15:28 UTC, Ostos-Alexander commented on homework2/ostos_task_2.html
> +
це бокові симетричні колонки, все про них описано в css

2017-03-17 16:49 UTC, Ostos-Alexander commented on homework2/ostos_task_2.html
> +    		<div class="text">Lorem Ipsum - це текст-"риба", що використовується в друкарстві та дизайні. Lorem Ipsum є, фактично, стандартною "рибою" аж з XVI сторіччя, коли невідомий друкар взяв шрифтову
згоден!
дивно, чому воно так залило в гітхаб, 
адже в мене в html-файлі все зроблено з абзацами

2017-03-17 21:04 UTC, Ostos-Alexander commented on homework2/ostos_task_2.css
> +}
не доля) бо тоді велосипед дуже контрастний виходить)
це сталося бо я без авокоду його робив

2017-03-18 14:02 UTC, pro100jas commented on homework2/ostos_task_2.css
>  	width: 131%;
В тебе головна сторінка не по центру, через те, що ти змінив width

2017-03-18 14:06 UTC, pro100jas commented on homework2/ostos_task_2.css
> +    margin-bottom: 40px;
можна використовувати 1 свойство марджин замість 3

2017-03-18 14:07 UTC, pro100jas commented on homework2/ostos_task_2.css
> +	padding-bottom: 12px;
паддінги також можна помістити в 1 свойство

2017-03-18 14:07 UTC, pro100jas commented on homework2/ostos_task_2.css
> +	padding-bottom: 7px;
читай вище

2017-03-18 14:07 UTC, pro100jas commented on homework2/ostos_task_2.css
> +	padding-bottom: 12px;
написав про паддінги вже

2017-03-18 14:08 UTC, pro100jas commented on homework2/ostos_task_2.css
> +	padding-bottom: 12px;
вище написав

2017-03-18 14:09 UTC, pro100jas commented on homework2/ostos_task_2.css
>  	padding-bottom: 12px;
написав про паддінги) юзай як 1 свойство

2017-03-18 14:10 UTC, pro100jas commented on homework2/ostos_task_2.css
>  }
в тебе в 3 классів однакове свойство, краще зроби 1 класс з цим свойством і напиши його там, де тобі треба

2017-03-19 20:07 UTC, pro100jas commented on homework2/ostos_task_2.css
> +	width: 130%;
убери його взагалі

2017-03-20 08:18 UTC, Ostos-Alexander commented on homework2/ostos_task_2.css
> +	width: 130%;
та неее) тоді взагалі головна сторінка вниз поїде
я це одразу пробував ще коли починав, по іншому не виходить

2017-03-24 10:21 UTC, egemon requested changes
Visible issues:
1) There is no right side margin (no grey background to the right of the main part)
2) when hover top menu - borders move all item to the right
3) hovering in the left menu changes cursor to pointer and text color on hover only on text, it should work on the full block, not only on text

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	width: 122%;
why? it is incorrect, you need grey to the left too.

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.aside1 {
don't create empty blocks. All you need here is just fixed width for container and margin: 0 auto; for it

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.page {
i mean fixed width and margin-0-auto for this container.

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	height: 950px;
don't use fixed height here. You should always take into account that text and content may vary so it should not go out from the box, rather it should move the box border and make it bigger

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	margin-left: 50px;
use shortcut property margin: 40px 50px 80px;
please read more about it

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +    display: inline-table;
wtf?

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	font-family: Arial;
use font-stacks here, I've told about it on previous lesson

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	background: -webkit-linear-gradient(45deg, rgba(69,68,68,1) 0%, rgba(94,94,94,1) 100%);
:+1: you can omit percents if they are 0 and 100

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	background-color: #ffffff;
it is white, probably you need black here right?

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding-left: 0;
please remove this and use normalize or reset css ok?

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	list-style-type: none;
this will do reset.css for you probably. Or you can set it to all li's like
li {
list-style: none
}

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	border-left: 1px solid #C0C0C0;
cool, but these borders add the width of box, so other boxes feel that and move to the right. you need on hover compensate this two pixels by smth else.

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	text-decoration: none;
this can be applied to all links like this:
a {
text-decoration: none
}

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.space {
remove this, all spaces between block should be done only with margins ok?

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.technics {
order of classes in CSS should be the same as order of these block in HTML

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding: 7px 80px 7px 20px;
:+1:

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	border-top: 1px solid #D3D3D3;
use here shortcut for border too

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding-right: 70px;
do you need to change right-padding on hover? why it so so big?

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	float: left;
you forget to clean after these floats

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding-left: 0;
no need, use reset.css instead

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.board li:last-child {
don't use tags selectors, only classes

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.footer1 {
when use inline-block you should not to forget to set font-size 0 to remove spaces between

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +	margin-top: 650px;
you need so big margin because you forgot to clear after floats, fix this

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.css
> +.footer_link_1_5 {
remove all these styles, they should be the same for all menu items. Copyright should be moved out from menu as it is not a part of menu. Try justify-content:space-between

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +	<link rel="stylesheet" type="text/css" href="ostos_task_2.css">
add reset css here

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +<aside class="page">
page is not aside, use main maybe

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +	<h1 class="fitness">Fitness</h1>
here should be image not just text, because we don't know what is the font. Moreover you should wrap image into link to make it clickable. It is not obvious but it is true for 99% of sites.

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +	<menu class="tape">
don't use menu - use ul>li

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +			<font ><a class="header_link" href="">Главная</a></font>
don't use font tag at all. It is deprecated and useless.

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +	<menu class="tape">
please read the article about BEM in chat and try to rename all classes.

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +	<div class="space"></div>
remove, use margins intead of this

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +			<li class="technics"><a class="click" href="">Ноутбуки</a>
please after reading BEM rename all classes in this HTML ok?

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +    	<aside class="photo">
it is not aside actually. Please use tags by it's purpouse. If you are not sure - use div

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +		<li class="diblock footer_link_1_5">
move copyright out of menu, but into footer - create separate container. Like this
footer> ( ul>li + div.copyright)

2017-03-24 10:21 UTC, egemon commented on homework2/ostos_task_2.html
> +		<li class="flexbox footer_link_1_5">
the same here

2017-05-03 11:15 UTC, egemon approved these changes

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +    margin: -8px 154px;
нужно избегать отрицательных марджинов!

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +	background-image: linear-gradient(to top, #444343 0%, #5e5e5e 100%);
:+1:

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +a {
Лучше собрать в начале файла все стили для тэгов

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +.board li {
не использовать вложенные селекторы. Дай этим элементам классы и обращайся по классам

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +.board li:last-child {
тут будет твой_клас:last-child

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding-right: 70px;
зачем нужен правый паддинг на ховер?

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding: 7px 80px 7px 20px;
не нужно такой большой правый паддинг - если текста станет больше - он тогда вылезет с таким паддингом. Оставь небольшой паддинг, просто чтобы текст в случае чего не прилип к правом краю

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +.clean {
обычно этот класс называют .clearfix

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +		font-size: 0;
выравняй эту строчку как все остальные

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +	font-size: 0;
вот это хорошо

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.css
> +	padding: 12px 20px 12px 47px;
старайся вместо одинаковых вертикальных паддингов обходится свойство line-height

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.html
> +	<link rel="stylesheet" type="text/css" href="css_reset.css">
сначала подключается ресет.css а потом твои стили. Иначе reset может перебить твои стили своими а ты хочпешь наоборот

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.html
> +		<li class="header__options">
лучше использовать header_list-item

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.html
> +			<li> <a class="board__item" href="">Ноутбуки</a> </li>
вот тут почему то у li не хватает классов

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.html
> +  		<div class="clean"></div>
не нужно дополнительный блок. Так тоже можно, но лучше использовать псевдоэлемент ::after

2017-05-03 11:15 UTC, egemon commented on homework2/ostos_task_2.html
> +    <div class="footer1">
слишком много контейнеров, у тебя тут footer1 содержит footer2. Думают это неправильно

2017-05-04 10:15 UTC, merged